version: '3.8'

services:
  app:
    build: .
    container_name: deathboard-app
    ports:
      - "3001:3001"
    restart: always
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql-n8n
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: catarino
      MYSQL_DATABASE: deathboard
    networks:
      - shared-net

networks:
  shared-net:
    external: true
