import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Death Board",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Navbar />
        <div className="dark:text-white h-[calc(100vh-5rem)] p-2 md:p-10">
          <div className="container mx-auto h-full">{children}</div>
        </div>
        <Toaster position="top-right" toastOptions={{ style: { background: "#1e293b", color: "#fff" } }} />
      </body>
    </html>
  );
}
